// export const CREATE_CONTACT = "CREATE_CONTACT";
// export const GET_CONTACT = "GET_CONTACT";
// export const UPDATE_CONTACT = "UPDATE_CONTACT";
// export const DELETE_CONTACT = "DELETE_CONTACT";
// export const SELECT_CONTACT = "SELECT_CONTACT";
// export const CLEAR_CONTACT = "CLEAR_CONTACT";
// export const DELETE_SELECTED_CONTACT = "DELETE_SELECTED_CONTACT";

export const  ADD_DETAIL = "ADD_DETAIL";
export const  GET_DETAIL = "GET_DETAIL";
export const  UPDATE_DETAIL = "UPDATE_DETAIL";
export const  DELETE_DETAIL = "DELETE_DETAIL";